"""Create Files table

Revision ID: 0554f22ee56e
Revises: d41d42b51378
Create Date: 2025-08-10 18:00:43.069722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0554f22ee56e'
down_revision = 'd41d42b51378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('technologies',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('github_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('github_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('technologies',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               nullable=False)

    op.drop_table('download_file')
    # ### end Alembic commands ###
