"""Create homepage content table

Revision ID: 532cfd684154
Revises: 0554f22ee56e
Create Date: 2025-08-12 18:49:48.616645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532cfd684154'
down_revision = '0554f22ee56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('download_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('homepage_content')
    # ### end Alembic commands ###
