name: Trigger Playwright Tests

on:
  push:
    branches:
      - develop

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to playwright-tests
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/Xela96/playwright-tests/dispatches \
            -d '{"event_type": "run-playwright-tests", "client_payload": {"environment": "local", "category": "all"}}'
